echo "Building..." &&
/usr/bin/java -jar /home/michal-wyszynski/.vscode/extensions/bowlerhatllc.vscode-as3mxml-1.22.0/bin/asconfigc.jar --sdk /home/michal-wyszynski/Downloads/AIRSDK_Linux --debug=true --project "/media/michal-wyszynski/Michał karta SD/reverse engineering/uconnect/uconnext/asconfig.json" --unpackage-anes=true &&
/usr/bin/java -jar /home/michal-wyszynski/.vscode/extensions/bowlerhatllc.vscode-as3mxml-1.22.0/bin/asconfigc.jar --sdk /home/michal-wyszynski/Downloads/AIRSDK_Linux --debug=true --project "/media/michal-wyszynski/Michał karta SD/reverse engineering/uconnect/uconnext/asconfig_systemui.json" --unpackage-anes=true &&
/usr/bin/java -jar /home/michal-wyszynski/.vscode/extensions/bowlerhatllc.vscode-as3mxml-1.22.0/bin/asconfigc.jar --sdk /home/michal-wyszynski/Downloads/AIRSDK_Linux --debug=true --project "/media/michal-wyszynski/Michał karta SD/reverse engineering/uconnect/uconnext/asconfig_testapp.json" --unpackage-anes=true &&
/usr/bin/java -jar /home/michal-wyszynski/.vscode/extensions/bowlerhatllc.vscode-as3mxml-1.22.0/bin/asconfigc.jar --sdk /home/michal-wyszynski/Downloads/AIRSDK_Linux --debug=true --project "/media/michal-wyszynski/Michał karta SD/reverse engineering/uconnect/uconnext/asconfig_musicapp.json" --unpackage-anes=true &&
/usr/bin/java -jar /home/michal-wyszynski/.vscode/extensions/bowlerhatllc.vscode-as3mxml-1.22.0/bin/asconfigc.jar --sdk /home/michal-wyszynski/Downloads/AIRSDK_Linux --debug=true --project "/media/michal-wyszynski/Michał karta SD/reverse engineering/uconnect/uconnext/asconfig_climateapp.json" --unpackage-anes=true &&
echo "Building done, removing artifacts" &&
rm bin/pkgs/systemui-app.xml && rm bin/pkgs/testapp-app.xml && rm bin/pkgs/musicapp-app.xml && rm bin/pkgs/climateapp-app.xml && rm -r bin/pkgs/pkgs && rm bin/pkgs/uConnext-app.xml &&
echo "Running..." &&
WINEDEBUG=-all wine "/media/michal-wyszynski/Michał karta SD/aplikacje/airsdk windows/bin/adl.exe" bin/uConnext-app.xml